openapi: 3.0.1
info:
  title: Enrich_API
  description: API Definition of Enrich_API
  version: 1.0.0
servers:
- url: http://localhost:8290/enrich
paths:
  /:
    post:
      responses:
        default:
          description: Default response
