openapi: 3.0.1
info:
  title: FetchingName_API
  description: API Definition of FetchingName_API
  version: 1.0.0
servers:
- url: http://localhost:8290/fullname
paths:
  /:
    post:
      responses:
        default:
          description: Default response
