openapi: 3.0.1
info:
  title: HelloWorld_API
  description: API Definition of HelloWorld_API
  version: 1.0.0
servers:
- url: http://localhost:8290/helloworld
paths:
  /:
    get:
      responses:
        default:
          description: Default response
