openapi: 3.0.1
info:
  title: Calculator_API
  description: API Definition of Calculator_API
  version: 1.0.0
servers:
- url: http://localhost:8290/result
paths:
  /:
    post:
      responses:
        default:
          description: Default response
